### ISSUE TITLE
build image came across this issue

### ISSUE THREAD

**Issue by xiaods** [okfn/docker-rt#1]
``` bash
2014/04/21 10:40:13 The command [/bin/sh -c make -C /src/${RT} testdeps 2>/dev/null | fgrep ...MISSING | cut -d' ' -f1 | sort -u | xargs c
panm] returned a non-zero code: 123
```

**Comment by nickstenning** [comment]
Yes, this is unfortunate, but as far as I know there's not a lot we can do. Installing perl packages unattended is notoriously painful. The only suggestion I can make is to retry the build until this works!

**Comment by xiaods** [comment]
@nickstenning thanks for your suggest. let me have a try.
